name: autofix.ci

on:
  workflow_dispatch:

jobs:

 autofix-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
        with:
          commit-message: "chore: apply automatic fixes"
