name: autofix.ci

on:
  workflow_dispatch:

jobs:

 autofix-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8
        with:
          commit-message: "chore: apply automatic fixes"
