name: build APK

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build-apk:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [temurin, zulu]
    
    steps: 
       - name: Checkout Repo
         uses: actions/checkout@v5
         with: 
           fetch-depth: 0

       - name: Setup Java 
         uses: actions/setup-java@v5 
         with: 
           distribution: "${{ matrix.version }}" 
           java-version: "17" 
  
       - name: Setup Gradle 
         uses: gradle/gradle-build-action@v3 
         with: 
           gradle-home-cache-cleanup: true

       - name: Pull Source Code
         run: |
           sudo apt install aria2 -y
           git clone https://github.com/ZTMIDGO/RWKV-Android/ source

       - name: Pull Model
         run: |
           aria2c -o model.onnx -d source/app/src/main/assets/model https://huggingface.co/TIEMING/rwkv-world-0.4B-onnx/resolve/main/model.onnx

       - name: Build with Gradle 
         run: | 
           cd source
           sudo chmod 777 -R ./* 
           ./gradlew clean assembleRelease 
  
       - name: Upload build artifact 
         uses: actions/upload-artifact@v5 
         with: 
           name: build-${{ matrix.version }}-${{ github.sha }}
           path: source/app/build/outputs/apk/release/*.apk
