name: build manager

on:

  workflow_dispatch:

jobs:

  build-manager:
    runs-on: ubuntu-latest
    
    steps: 
       - name: Checkout Repo
         uses: actions/checkout@v3 
         with: 
           fetch-depth: 0

       - name: Setup Java 
         uses: actions/setup-java@v3 
         with: 
           distribution: "temurin" 
           java-version: "17" 
  
       - name: Setup Gradle 
         uses: gradle/gradle-build-action@v2 
         with: 
           gradle-home-cache-cleanup: true

       - name: Pull Source Code
         run: |
           sudo apt install aria2 -y
           git clone https://github.com/ZTMIDGO/RWKV-Android/ source

       - name: Pull Model
         run: |
           aria2c -d source/app/src/main/assets/model https://huggingface.co/TIEMING/rwkv-world-0.4B-onnx/resolve/main/model.onnx

       - name: Build with Gradle 
         run: | 
           cd source
           sudo chmod 777 -R -v ./*
           echo 'org.gradle.parallel=true' >> gradle.properties 
           echo 'org.gradle.vfs.watch=true' >> gradle.properties 
           echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties 
           echo 'android.native.buildOutput=verbose' >> gradle.properties 
           sed -i 's/org.gradle.configuration-cache=true//g' gradle.properties 
           ./gradlew clean assembleRelease 
  
       - name: Upload build artifact 
         uses: actions/upload-artifact@v3 
         with: 
           name: build
           path: source/app/build/outputs/apk/release/*.apk
          
